name: Periodic Job

on:
  push:
    branches: [ master ]
  schedule:
    # 5pm on weekday UTC -> 9AM pacific time
    - cron: "0 17 * * 1-5"

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Use Node.js
      uses: actions/setup-node@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Generate data
      run: |
        make data
    - name: Post slack notification
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      run: |
        python slack_runner.py
